# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
      venv/|
  )$

repos:
  - repo: https://github.com/mxmlnrdr/clang_tidy_hook
    rev: v0.2.1
    hooks:
      - id: clang-tidy
        name: clang-tidy
        description: Find warnings/errors in C, C++, and Objective-C code
        entry: clang-tidy-hook
        language: python
        types_or: [c, c++, c#, objective-c]
        verbose: true
